% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{float}
\usepackage{booktabs}
\usepackage{lscape}
\usepackage{mathtools}
\usepackage{amsmath}
\newcommand{\blandscape}{\begin{landscape}}
\newcommand{\elandscape}{\end{landscape}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Cosy analysis},
  pdfauthor={Louise Bernard},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Cosy analysis}
\author{Louise Bernard}
\date{2024-05-31}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Introduction}\label{introduction}

Cosy is a Time of Use (TOU) Tariff specifically designed for heat pump users. The tariff includes two three-hour ``Cosy'' periods (morning and afternoon) with reduced unit rates, and a three-hour peak period with a higher unit rate. All other hours are billed at the customers' typical ``Flexible Octopus'' unit rate. The goal of this analysis is to evaluate whether Cosy enables customers to optimize their heat pump usage by shifting their electricity consumption away from peak periods, which are most polluting for the grid, while also saving money.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/Cosy Tariff Screenshot Dec 12} 

}

\caption{Cosy Periods}\label{fig:cosy}
\end{figure}

To achieve this, we analyzed the electricity and gas data for 5,196 Cosy customers using a Difference-in-Differences (DiD) estimator. This approach controls for weather, day, and customer fixed effects. In simpler terms, we used ``later'' Cosy adopters as a counterfactual for earlier Cosy adopters to understand the causal impact of Cosy adoption on consumption. To address the weakness of the two ways dixed effect DiD estimator hightlighted by the recent literature, we also estimate the Goodman Bacon decomposition and Callaway and Sant'Anna dynamic estimators.

Our analysis covers extended pre- and post-adoption periods, not just the weeks immediately before and after adoption. Many customers in our sample have two winters of data on Cosy, allowing us to observe stable and persistent effects over time.

We find that Cosy causes:

\begin{itemize}
\tightlist
\item
  Much higher electrity consumption in Morning Cosy period (three hours: 04:00 - 07:00, 12.6p/kWh): + 3.1 kWh (increase)
  Pre-Cosy adoption average is 2.3kWh, so this increase is a more than doubling effect.
\item
  Much higher electricy consumption in afternoon Cosy-period (three hours: 13:00 - 16:00, 12.6p/kWh): + 1.8 kWh (increase)
  Pre-Cosy adoption average is 2kWh, so this increase is almost doubling.
\item
  Much lower peak elec consumption (three hours: 16:00 - 19:00, 37.3p/kWh): -1.2 kWh (decrease)
  Pre-Cosy adoption average is 2.2kWh, so this decrease is halving their peak consumption.
\item
  Slightly lower electricity consumption during all other times (15 hours, 25.72p/kWh):
  -2.8 kWh (decrease)
  Pre-Cosy adoption average is 11.2kWh, so this decrease is still a substantial \textasciitilde25\% reduction.
\end{itemize}

These effects are yearly average - load shifting towards off peak time is twice as high during Winter while peak avoidance persist during non-winter months.

Back-of-envelope calculations (assuming customer was on Flexible Octopus before) indicate that the above effects sum to £0.50 per day savings, which is in a similar ballpack of annual savings as those OE have estimated. (We estimate \textasciitilde£177 per year, OE estimates \textasciitilde£220 per year.) OE assumes no change in total consumption, which may not be a safe assumption.

Indeed, all of the above estimates are in a similar direction and ballpack as OE's analysis, which was based on earlier adopters and only examined short-term impacts. We believe our analysis is much more robust, but it's comforting (in both directions) to see the high-level concordance.

As noted above, we find that the Cosy results are stable and persistent over at least a year, which is a new result.

The rest of the paper is structured as follow: First, we present summary statistics in Section \ref{sec:sumstats}, the timeline of Cosy adoptions, how many customers stayed on Cosy after adopting it and the likelihood to stay on a smart tariff. Then we show the main results of our difference in difference analysis and Callaway and Sant'Anna estimations in Section \ref{sec:results} and finally, we summarise the main results in the conclusion section \ref{sec:conclusion}.

\section{Summary statistics}\label{sec:sumstats}

\subsection{Timeline of Cosy adoption}\label{timeline-of-cosy-adoption}

The tariff was launched in December 2022. Adoption were stable for the first year and peaked during Winter 2023-2024 just after heatpumps' interest peaked due to increase in Gas Boiler Upgrade Scheme.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/weekly_adoptions} 

}

\caption{Weekly Adoption}\label{fig:weekly-adoption}
\end{figure}

Out of our sample of 5,196 customers, 4,465 switched to Cosy and stayed on Cosy. Another 394 tried and then switched. Finally, 337 have multiple contracts.

The vast majority of Cosy adopters were previously enrolled in either the Octopus Flexible or a Fixed tariff before switching to Cosy as shown in Figure \ref{fig:top10before}.

Customers that switched after adopting to Cosy seem more likely to adopt another smart tariffs as shown in Figure \ref{fig:top10after}.

Overall, prior to Cosy adoption, 91.2\% of adopters were on a non-smart tariff\footnote{No Time of Use or Price Tracker}. After adopting Cosy, only 2\% revert back to a non-smart tariff.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/top10_before_cosy} 

}

\caption{Top 10 Tariffs Before Adopting Cosy}\label{fig:top10before}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/top10_after_cosy} 

}

\caption{Top 10 Tariffs After Adopting Cosy}\label{fig:top10after}
\end{figure}

\subsection{Cosy adopters}\label{cosy-adopters}

In this section, we compare early Cosy adopters to later adopters by regressing the week of adoption (0 for customers that have adopted in the first week up to 65 weeks after the launch of the tariff). Toi this end, we use the Domus dataset that has information on the location of the customers, characteristics of the house as well as Octopus Energy data on customers previous electricity contracts.

Unsurprisingly, we find that early adopters are slightly different from later adopters, and reflecting that they are more energy engaged (a quality that we can not observe). We find that early adopters are more likely to live in urban areas, have a higher estimated annual energy consumption and more energy efficient house. For this reason, we know that regressing tariff adoption on electricity consumption could bias our estimates as we need to control for difference in levels between early and later adopters.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/early_versus_late} 

}

\caption{Early versus Late Adopters}\label{fig:earlylate}
\end{figure}

\section{Empirical analysis}\label{sec:results}

\subsection{Main Difference in Differences}\label{main-difference-in-differences}

To address these confounding factors, we implemented a difference-in-difference analysis, controlling for time fixed effects (to remove any general upward trends in consumption) and customer fixed effects (to account for differences in electricity consumption levels).

Another threat to causal inference is the installation of heat pumps. This factor is not captured by our fixed effects, as it varies across customers and time periods, potentially biasing our coefficients downward since heat pump installation typically occurs before Cosy adoption. We perform robustness checks in \ref{tab:did-hp-install} to address this issue.

We run the following model by period and on total daily consumption for all customers that have adopted Cosy in the past year:

\begin{equation} 
\label{simple-did}
Consumption_{it} = \alpha OnCosy_{it} + \beta HDD_{it} + \delta_t +  \gamma_i +  \epsilon_{it} 
\end{equation}

with:

\begin{itemize}
\tightlist
\item
  \(Consumption_{it}\) - electricty consumption in kWh (Table 1) and as share of daily consumption (Table 2) for customer \(i\) on day \(t\)
\item
  \(OnCosy_{it}\) a dummy variable equals 1 if the customer is on Cosy, 0 otherwise
\item
  \(HDD_{it}\) the average heating degrees in day \(t\) and the GSP of customer \(i\)
\item
  \(\delta_t\), \(\gamma_i\) are day \(t\) and customer \(i\) fixed effects
  The standard errors are clustered at the customer (MPAN) level.
\end{itemize}

Table \ref{tab:did-main} presents the effects of switching to the ``Cosy'' rate on customers' electricity consumption across different times of the day using consumption in kilowatt-hours (kWh) per period, along with a separate analysis for overall daily consumption. Here's a summary of the findings:

\begin{itemize}
\tightlist
\item
  \textbf{Afternoon Cosy (Model 1):} Customers on the Cosy rate increased their electricity consumption by an average of 1.8kWh during the afternoon cosy period.
\item
  \textbf{Morning Cosy (Model 2):} There was an even larger increase in consumption during the morning cosy period, with customers consuming an additional 3.1kWh on average.
\item
  \textbf{Other Time (Model 3):} Conversely, consumption during other times of the day not specified as cosy morning or afternoon decreased by 2.8kWh.
\item
  \textbf{Peak Rate (Model 4):} Consumption during peak rate times decreased by 1.2kWh, showing that customers are reducing their usage during more expensive or high-demand periods.
\item
  \textbf{Overall Daily Consumption (Model 5):} Despite these shifts in consumption patterns throughout the day, the overall daily consumption increased slightly by 0.89 kWh, suggesting that while there's a redistribution of when electricity is used, the total daily usage still went up on the Cosy rate.
\end{itemize}

All of these coefficients are statistically significant at the 1 percent significance level.

In summary, switching to the Cosy rate appears to effectively encourage customers to increase their electricity consumption during incentivised periods (cosy morning and afternoon) while decreasing usage during peak and other times, with an overall slight increase in daily consumption.

We shown in the Appendix robustness checks controlling for Heat Pump installation (Table \ref{tab:did-hp-install}).

\begin{landscape}
\input{"../tables/did.tex"}
\end{landscape}

We present the results of the same regression by half hour average by period and by half hour in Figures \ref{fig:didhalf} and \ref{fig:didhalf2}.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/consumption_did} 

}

\caption{Difference-in-Differences Results by Half Hour Average (by Period)}\label{fig:didhalf}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/hourly_consumption} 

}

\caption{Difference-in-Differences Results by Half Hour Average (by Half Hour)}\label{fig:didhalf2}
\end{figure}

\subsection{Difference in Differences by Seasons}\label{difference-in-differences-by-seasons}

In this section, we explore the impact of Cosy on electricity consumption throughout the year. To achieve this, we enhance the original Equation @\ref(eq:simple-did) by including an interaction term with Winter months (defined as November through March). We continue to control for customers fixed effects (MPAN), date, and heating degree days (HDD), ensuring that our coefficients reflect the average effect on electricity consumption while accounting for particularly cold days, time trends, and differences in customer consumption levels.

Table \ref{tab:did-seasons} presents the results of this analysis. The dependent variables are the consumption in kWh for different periods of the day: Afternoon Cosy, Morning Cosy, Other periods, Peak Rate, and total daily consumption.

The coefficient \(OnCosy_{it}\) shows the impact of Cosy adoption on electricity consumption during non-Winter months. \(Winter \times OnCosy_{it}\) captures the additional impact of Cosy adoption during Winter months. To find the total effect of Cosy during Winter, both coefficients need to be summed.

Comparing the winter-specific results in Table \ref{tab:did-seasons} with the annual results in Table \ref{tab:did-main}

\begin{itemize}
\item
  \textbf{Afternoon Cosy (Model 1):} The impact of switching to Cosy increases consumption by 1.750 kWh during the afternoon Cosy rate time. However, when examined by season, the impact during non-winter months is relatively small, with a 0.570 kWh increase per period, and much larger during winter, with an additional 2.883 kWh. This indicates that most of the impact occurs through using the heat pump for heating, although there is still some load shifting during non-winter months, likely through smaller appliances.
\item
  \textbf{Morning Cosy (Model 2):} Similarly to the Afternoon period, Cosy adoption increases consumption by 3.127 kWh during the morning Cosy rate time. Seasonally, the non-winter impact is 1.847 kWh, while the additional winter impact is 3.129 kWh, totaling 4.976 kWh. This suggests that both Cosy periods are used both for heating and smart appliances.
\item
  \textbf{Other Periods (Model 3):} Overall, Cosy adoption decreases consumption by 2.841 kWh during other periods. In non-winter months, the reduction is slightly less at -2.102 kWh, and during winter, the additional reduction is -1.799 kWh, totaling -3.901 kWh.
\item
  \textbf{Peak Rate (Model 4):} The impact of Cosy adoption decreases consumption by 1.244 kWh during peak rate times annually. The non-winter reduction is -0.776 kWh, with an additional winter reduction of -1.143 kWh, resulting in a total winter reduction of -1.919 kWh. This shows a significant shift in consumption away from peak times, more pronounced in winter.
\item
  \textbf{Total Daily Consumption (Model 5):} Across the year, Cosy adoption results in a 0.890 kWh increase in total daily consumption. During non-winter months, there is a non-significant decrease of -0.395 kWh, but during winter, there is a significant increase of 3.127 kWh, leading to a total winter effect of 2.732 kWh. This reflects the substantial impact of Cosy on overall consumption, primarily due to increased heating requirements in winter.
\end{itemize}

Our analysis reveals significant load shifting from both peak and other times to the two Cosy periods. Interestingly, this effect persists during the summer, indicating that Cosy adopters shift not only heating but also other appliance usage. This finding suggests the potential for further comparison with load shifting patterns observed under other tariffs.

In terms of general consumption, the increase is evident only during the winter. The magnitude and persistence of the Cosy effect, as discussed in the Section \ref{sec:santanna}, align with the expected outcomes of using smart thermostats. This observation, consistent with previous studies on time-of-use tariffs and smart thermostats, suggests that people are encouraged to shift consumption away from expensive periods while also using smart thermostats to maximize comfort---ultimately increasing total energy consumption (Brandon et al., 2021; Blonz et al., 2021).

\begin{landscape}
\input{"../tables/did_seasons.tex"}
\end{landscape}

In order to understand better the relationship between load shifting induced by Cosy rates and seasonal variations, we plot below the interaction between average outside temperature in degrees\footnote{Measured at the GSP level} and Cosy adoption. We control for consumer and day fixed effect, meaning that we only capture the additional impact of a change in temperature after adopting Cosy. The direct impact of temperature on electricity consumption is not plotted in this graph.

For both Cosy periods, we find that the colder the days, the more shift in consumption takes place. The relationship between increase shifting and temperature stops around 14 degrees giving credence that this extra shifting is heating from peak time being displaced at cheap periods.

For peak time rate, we observe the reverse relationship where more and more consumption is shifted away after adoption as temperatures get colder. There does not seem to be a point where customers are not being able to shift more, but we do not observe that many colder days.

For all periods, we observe that there are around 4 kWh of electricity that is always shifted away from peak and other time periods towards the cheap Cosy periods. That consumption do not seem to be related to heating.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/temperature_morning_cosy} 

}

\caption{Impact of Temperature on Morning Cosy Consumption}\label{fig:temp2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/temperature_afternoon_cosy} 

}

\caption{Impact of Temperature on Afternoon Cosy Consumption}\label{fig:temp1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/temperature_peak_rate} 

}

\caption{Impact of Temperature on Peak Rate Consumption}\label{fig:temp3}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/temperature_other} 

}

\caption{Impact of Temperature on Other Rate Consumption}\label{fig:temp4}
\end{figure}

\subsection{Heterogeneity analysis}\label{heterogeneity-analysis}

The heterogeneity analysis divided into three groups based on high annual electricity consumption (EAC), Energy Performance Certificate (EPC) scores, and whether or not the last tariff before adopting the Cosy rate was a variable , yields insightful results on peak time consumption patterns.

\textbf{Impact of Annual Energy Consumption (EAC) on total Peak Time Consumption} The interaction term \({EAC in mWh} \times OnCosy_{it}\) shows a significant negative effect (-0.0804 kWh per period), indicating that higher annual energy consumption is associated with a larger reduction in peak time consumption. For context, the median EAC in mWh is 5.258 and the mean is 6.106, with the distribution being quite skewed to the left. Therefore, the average treatment effect is a reduction of 1.2 kWh, but large consumers are driving this result.

\textbf{Impact of Energy Performance Certificate (EPC) Ratings:} The interaction terms between OnCosy and various EPC ratings (B to G) show that there is no significant difference in peak time consumption reduction by EPC letter. This finding suggests that the energy efficiency of the home, as indicated by EPC ratings, does not significantly affect the impact of Cosy adoption on peak time consumption.

\textbf{Impact of Heatloss Ratings:} The interaction terms between OnCosy and heatloss rating decile show that houses with poorer rating are successfully able to shift energy consumption away from peak time to cheaper cosy periods.

\textbf{Regional variations:} The interaction term \(Region \times OnCosy_{it}\) is not signficant for any of the periods, showing little regional variations to Cosy once we control for MPAN and day fixed effects.

\textbf{Impact of Previous Variable Rate Tariff:} The interaction term \(Prev Is Variable \times OnCosy_{it}\) is significant (-0.1984 kWh per period), indicating that customers previously on a variable rate tariff (e.g., time of use, not flexible Octopus) reduce their peak time consumption significantly more after adopting Cosy. However, these customers constitute a minority (8.7\% of the previous contact), so they are not driving the average effect up.

The heterogeneity analysis shows that Cosy adoption leads to a significant reduction in peak time consumption, with the magnitude of the reduction varying based on annual energy consumption and previous tariff types. Higher annual energy consumption is associated with larger reductions in peak time usage, suggesting that heavy users benefit more from load shifting. Previous variable rate tariff users also experience greater reductions, indicating they might be more responsive to the incentives provided by Cosy. However, the impact of Cosy adoption does not significantly differ by EPC ratings, suggesting that home energy efficiency does not play a major role in the effectiveness of Cosy in reducing peak time consumption. However, the heterogeneity on heatloss shows that houses with higher heatloss are able to shift away their heating from peak to cheaper periods.

\subsubsection{Estimated Annual Consumption (EAC)}\label{estimated-annual-consumption-eac}

In this section, we show the interaction between EAC and adopting Cosy on total consumption and share of daily consumption for each period. We control for day and customers fixed effect, meaning that the coefficients plotted only represent the additional impact of belonging to one of the EAC decile on electricity consumption after adopting Cosy \textasciitilde{} not the direct relationship between EAC and energy consumption.

We find that while higher decile EACs shift more electricity from peak time to morning and afternoon Cosy periods, the relationship with the relative share of electricity consumption at peak time is more complexe: it is increasing for the first decile and decrease for the last ones. It probably represents a complexe relationship between EAC and unobservable factors: presence of other LCTs, income.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/eac_morning_cosy} 

}

\caption{Impact of EAC on Morning Cosy Consumption}\label{fig:eac1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/eac_afternoon_cosy} 

}

\caption{Impact of EAC on Morning Cosy Consumption}\label{fig:eac2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/eac_peak_rate} 

}

\caption{Impact of EAC on Morning Cosy Consumption}\label{fig:eac3}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/eac_other} 

}

\caption{Impact of EAC on Morning Cosy Consumption}\label{fig:eac4}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/eac_share_morning_cosy} 

}

\caption{Impact of EAC on Share of Morning Cosy Consumption}\label{fig:eac1share}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/eac_share_afternoon_cosy} 

}

\caption{Impact of EAC on Share of Afternnon Cosy Consumption}\label{fig:eac2share}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/eac_share_peak_rate} 

}

\caption{Impact of EAC on Share of Peak Rate Consumption}\label{fig:eac3share}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/eac_share_other} 

}

\caption{Impact of EAC on Share of Other periods Consumption}\label{fig:eac4share}
\end{figure}

\subsubsection{Energy efficiency}\label{energy-efficiency}

We perform the same heterogeneity analysis on EPC letter. We plot the coefficients on the interaction between EPC letter and adopting Cosy. As before, we hightlight that these coefficients do not include the direct impact of better EPC on energy consumption. We do not find strong differences in ability to switch energy consumption away from peak to Cosy periods by EPC (houses with a lower EPC rating seem to be able to shift less in the morning and peak, but the differences are not statistically significant). As a word of caution, EPC might not reflect well heatloss, most houses in our datasets have a EPC rating of D or above and people that have adopted Cosy might know their ability to shift prior to adoption.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/epc_morning_cosy} 

}

\caption{Impact of EPC on Morning Cosy Consumption}\label{fig:epc1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/epc_afternoon_cosy} 

}

\caption{Impact of EPC on Morning Cosy Consumption}\label{fig:epc2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/epc_peak_rate} 

}

\caption{Impact of EPC on Morning Cosy Consumption}\label{fig:epc3}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/epc_other} 

}

\caption{Impact of EPC on Morning Cosy Consumption}\label{fig:epc4}
\end{figure}

\subsubsection{Heatloss}\label{heatloss}

In order to look more closely whether or not houses with poorer insulation can provide flexibility, we use a subset of customers for which Octopus Energy has calculated their heatloss rate.

As before, we plot the interaction between heatloss rate decile and adopting Cosy. We find that houses with greater heatloss rate have more heating to shift around, meaning that they are able to shift more energy consumption away from peak rate to cosy periods. On ther hand, houses with low rate of heatloss are barely able to shift any heating around. The only impact of adopting Cosy is through the decrease in peak consumption observed at any temperature.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/heatloss_morning_cosy} 

}

\caption{Impact of Heatloss on Morning Cosy Consumption}\label{fig:heatloss1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/heatloss_afternoon_cosy} 

}

\caption{Impact of Heatloss on Afternoon Cosy Consumption}\label{fig:heatloss2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/heatloss_peak_rate} 

}

\caption{Impact of Heatloss on Peak Rate Consumption}\label{fig:heatloss3}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/heatloss_other} 

}

\caption{Impact of Heatloss on Other Period Consumption}\label{fig:heatloss4}
\end{figure}

\subsubsection{Regions}\label{regions}

Finally, we plot the interaction between customers' regions and adopting Cosy. In this regressions, we control for days and customers fixed effects, and isolate the impact of adopting Cosy. We compare all regional differences to our omitted base region, East Midlands.
We do not find any regional difference as shown in Table \ref{tab:regionaldid}.

\begin{landscape}
\input{"../tables/did_region.tex"}
\end{landscape}

\subsubsection{Variable Tariff}\label{variable-tariff}

We show in Table \ref{tab:prevvar} that customers that switched from a variable tariff are more able to switch consumption towards the cheaper periods. It could be due to the presence of additional LCTs that prompted the original change before moving to Cosy.

\begin{landscape}
\input{"../tables/did_prevar.tex"}
\end{landscape}

\subsection{Callaway Sant'Anna DiD}\label{sec:santanna}

In this section, we present the results of the Callaway and Sant'Anna estimator. It is a method used for estimating treatment effects in settings with staggered treatment adoption, where different units (such as individuals, firms, or regions) receive the treatment at different times, exactly as for the adoption of Cosy. This estimator addresses some of the limitations of traditional Difference-in-Differences (DiD) methods as presented in the Appendix \ref{sec:baconexplanation}.

To implement this estimator, we need to aggregate at the data at the week level. This aggregation may smooth out some of the daily volatility but still captures broader trends.

The Callaway and Sant'Anna estimator provides a framework for estimating average treatment effects on the treated (ATT) in the presence of staggered treatment adoption.

For this analysis, each customer is assigned to a cohort based on their week of adoption. For each treated group, construct a counterfactual outcome using units that have not yet received the treatment at that time. For instance, to estimate the effect for those treated in 2022, use the units that are not treated until 2023 or later as a control group. It avoids the bias created by the difference in differences estimator which also compared late treated versus early treated.

For each timing group, estimate the ATT by comparing the post-treatment outcomes of the treated units to the outcomes of the control group. This can be done using standard DiD techniques within each subgroup.

Finally, we combine the group-specific ATT estimates to obtain an overall ATT. The aggregation can be done using weights that reflect the size or importance of each timing group.

\subsubsection{Overall ATT (Average Treatment Effect on the Treated)}\label{overall-att-average-treatment-effect-on-the-treated}

We first present the overall ATT as they are the most comparable to the difference in differences estimator.

For the DiD coefficients (measured per period): the Afternoon Cosy period shows an increase of 1.75 kWh, the Morning Cosy period shows an increase of 3.127 kWh, the Other period shows a decrease of 2.841 kWh, and the Peak Rate period shows a decrease of 1.244 kWh. The overall daily consumption increase is 1.073 kWh.

For the Sant'Anna and Callway estimators resized as daily coefficients: the Afternoon Cosy period shows an increase of 2.33 kWh/day, the Morning Cosy period shows an increase of 3.41 kWh/day, the Other period shows a decrease of 2.61 kWh/day, and the Peak Rate period shows a decrease of 1.34 kWh/day. The overall daily consumption increase is 1.79 kWh/day.

The comparison indicates that the Callaway and Sant'Anna coefficients generally are in accordance with the difference in differences estimate with similar confidence intervals. They suggest a slightly stronger effect of the Cosy rate on altering electricity consumption patterns across different periods compared to the initial coefficients provided. This includes larger increases in consumption during Cosy periods and a slightly greater overall daily consumption increase. It makes sense as the traditional two way fixed effects difference in differences estimates are biasing downward the estimates by comparing late adoptors to early adoptors.

\subsubsection{Group and Calendar ATT}\label{group-and-calendar-att}

In the graphs below, we show the calender ATT for each cohort (starting from early adopters in light blue to late adopters in dark blue), for each week post Cosy adoption.

Early adopters have sighly larger load shifting than later adopters which is consistent with them having higher EAC.

There are clear seasonable effect for all cohorts.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/monthly_att_morning_cosy} 

}

\caption{Group and Calendar ATT - Morning Cosy}\label{fig:calgroup1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/monthly_att_afternoon_cosy} 

}

\caption{Group and Calendar ATT - Afternoon Cosy}\label{fig:calgroup2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/monthly_att_peak_rate} 

}

\caption{Calendar and Group ATT - Peak Rate}\label{fig:calgroup3}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/monthly_att_other} 

}

\caption{Calendar and Group ATT - Other Rate}\label{fig:calgroup4}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/monthly_att_overall} 

}

\caption{Calendar and Group ATT - Daily Overall}\label{fig:calgroup5}
\end{figure}

\subsubsection{Dynamic ATT}\label{dynamic-att}

Similar to the event study approach, dynamic ATT analyzes how the treatment effect changes over time, offering insights into whether the impact of Cosy grows stronger, weaker, or remains consistent in the weeks following adoption. This can help identify any adaptation period or delayed effects.

The x-axis represents weeks since adoption. The y-axis is daily consumption per period in kWh.

In Figures \ref{fig:dynamic1}, \ref{fig:dynamic2}, \ref{fig:dynamic3}, \ref{fig:dynamic4} and \ref{fig:dynamic5}, it is clear that there are no pre-trend adoption effects (the confidence intervals for the coefficients for weeks prior to adoption in red includes 0). Additionally, we observe a seasonal pattern, with more customers switching to Cosy before Winter, which overlaps with the impact of weekly adoption rates. We further investigate these effects in the calendar and cohort analysis below.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/plot_Afternoon Cosy} 

}

\caption{Dynamic ATT - Afternoon Cosy}\label{fig:dynamic1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/plot_Morning Cosy} 

}

\caption{Dynamic ATT - Morning Cosy}\label{fig:dynamic2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/plot_Peak Rate} 

}

\caption{Dynamic ATT - Peak Rate}\label{fig:dynamic3}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/plot_Other} 

}

\caption{Dynamic ATT - Other Rate}\label{fig:dynamic4}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/plot_Overall} 

}

\caption{Dynamic ATT - Daily Overall}\label{fig:dynamic5}
\end{figure}

\subsubsection{Group ATT}\label{group-att}

This analysis examines the treatment effect across different adoption periods, from early to later adopters.

The x-axis represents the treatment effect estimate for each treated cohort, while the y-axis indicates the first week of adoption. In our sample, we observe customers from up to a year before their adoption, so the first week of adoption is labeled as week 52 and the last as week 115.

The results show that the treatment effect is relatively smaller for those who had more weeks of treatment during the summer. In contrast, the later cohorts, who were treated primarily during the winter, exhibit a larger effect.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/groupplot_Afternoon Cosy} 

}

\caption{Group ATT - Afternoon Cosy}\label{fig:Group1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/groupplot_Morning Cosy} 

}

\caption{Group ATT - Morning Cosy}\label{fig:Group2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/groupplot_Peak Rate} 

}

\caption{Group ATT - Peak Rate}\label{fig:Group3}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/groupplot_Other} 

}

\caption{Group ATT - Other Rate}\label{fig:Group4}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/groupplot_Overall} 

}

\caption{Group ATT - Daily Overall}\label{fig:Group5}
\end{figure}

\subsubsection{Calendar ATT}\label{calendar-att}

This section focuses on the treatment effect relative to the calendar time.

The x-axis represents the treatment effect estimate for each week, starting from week 52 in our dataset, which corresponds to the tariff launch. The y-axis represents daily consumption in kWh.

As shown in Figures \ref{fig:cal1} and \ref{fig:cal2}, the effect of shifting to cheaper Cosy periods is concentrated during the autumn and winter seasons and is absent during the summer months.

However, shifting away from peak and other times of the day is present all year long, with a stronger effect during the winter months, as illustrated in Figures \ref{fig:cal3} and \ref{fig:cal4}.

Finally, the increase in total daily consumption is also concentrated during the winter months, particularly during the most recent winter (2023-2024), as shown in Figure \ref{fig:cal5}.

Overall, these results align well with the main and seasonal Difference-in-Differences analyses, indicating that the effects of Cosy adoption are not only substantial but also persistent over time.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/calendarplot_Afternoon Cosy} 

}

\caption{Calendar ATT - Afternoon Cosy}\label{fig:cal1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/calendarplot_Morning Cosy} 

}

\caption{Calendar ATT - Morning Cosy}\label{fig:cal2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/calendarplot_Peak Rate} 

}

\caption{Calendar ATT - Peak Rate}\label{fig:cal3}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/calendarplot_Other} 

}

\caption{Calendar ATT - Other Rate}\label{fig:cal4}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/calendarplot_Overall} 

}

\caption{Calendar ATT - Daily Overall}\label{fig:cal5}
\end{figure}

\section{Conclusion}\label{sec:conclusion}

This paper provides a comprehensive analysis of the impact of the Cosy rate on electricity consumption patterns, utilizing the latest methods in staggered adoption analysis to ensure robust results. Our findings highlight several key points:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Strong Effect on Shifting Consumption Away from Peak Periods:}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  The adoption of Cosy significantly shifts electricity consumption away from peak periods. This effect is evident throughout the year, indicating that Cosy effectively encourages users to avoid high-cost periods.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Persistence Over Time:}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  The impact of Cosy adoption is persistent, demonstrating lasting changes in consumption behavior well beyond the initial adoption phase. This persistence underscores the potential for sustained demand-side management through time-of-use tariffs.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \textbf{Seasonal Variations:}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  The effects of Cosy are particularly pronounced during the winter months, where the shift in consumption is more substantial. However, there is also evidence of peak avoidance during other months, highlighting the versatility and effectiveness of the tariff across different seasons.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  \textbf{Mor Flexibility for Houses with Higher Heatloss}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Our analysis reveals that consumers with higher heatloss tend to shift their consumption more significantly than customers with better insulated houses.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  \textbf{Enhanced Shifting by Time-of-Use Tariff Users:}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Customers who previously used time-of-use tariffs exhibit even greater shifts in their consumption patterns upon adopting Cosy. This finding suggests that these users are already accustomed to adjusting their usage in response to price signals, making them more adept at optimizing their consumption under the new tariff.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  \textbf{Rigorous Analytical Methods:}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Our study employs the most rigorous methods available for analyzing staggered treatment adoption, including the Callaway and Sant'Anna estimator and the Goodman-Bacon decomposition. These methods ensure that our results are robust and account for variations in treatment timing and heterogeneity in treatment effects.
\end{itemize}

In summary, the Cosy rate has a substantial and lasting impact on shifting electricity consumption away from peak periods, with particularly strong effects during the winter months. Larger consumers and those previously on time-of-use tariffs show the most significant shifts, indicating the potential for targeted demand-side management strategies.

\appendix
\section*{Appendix}
\addcontentsline{toc}{section}{Appendices}
\renewcommand{\thesubsection}{\Alph{subsection}}

\subsection*{Goodman Bacon Decomposition \{\#sec:baconexplanation\}}\label{goodman-bacon-decomposition-secbaconexplanation}
\addcontentsline{toc}{subsection}{Goodman Bacon Decomposition \{\#sec:baconexplanation\}}

In this section, we use the Goodman-Bacon Decomposition to understand the contributions of different sources of variation in a Difference-in-Differences (DiD) analysis. It decomposes the overall treatment effect estimated by DiD into its constituent parts, allowing researchers to identify which comparisons (such as those between treated and untreated groups at different times) drive the overall estimate.

To construct the Goodman-Bacon Decomposition, we need to restrict our dataset to customers for whom the treatment is increasing monotonically (people that switched to Cosy and stayed) and for whom we observe all treatment periods. Therefore, we limit our data to after October 2023. This gives us a dataset of 2814 customers. We aggregate the observations at the weekly level for ease of computing (there too many comparisons if we use daily adoption data). We show here the results for Peak Rate period analysis.
Even with the restriction we had to impose, the two way fixed effect difference-in-differences estimates recreated from the Bacon decomposition (-8.97 kWh per week) is very close to the ones from our main analysis (-1.244 kWh per day times 7 \textasciitilde{} -8.708 kWh per week).

The Bacon decomposition summary is as follows:

\begin{table}[htbp]
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}{lrr}
\toprule
Type & Weight & Avg\_ES \\
\midrule
\rowcolor{gray!10} Earlier vs Later Treated & 0.1411035 & -12.031270 \\
Later vs Always Treated & 0.6338757 & -7.531177 \\
\rowcolor{gray!10} Later vs Earlier Treated & 0.2204715 & -8.606004 \\
Treated vs Untreated & 0.0045493 & -6.535066 \\
\bottomrule
\end{tabular}}
\end{table}

\textbf{Earlier vs Later Treated:} comparison shows a significant negative effect size, indicating that those treated earlier had a greater reduction in electricity consumption compared to those treated later. The weight suggests this comparison contributes 14.1\% to the overall treatment effect.

\textbf{Later vs Always Treated:} is the most heavily weighted comparison, contributing 63.4\% to the overall effect. It indicates that those treated later saw a reduction in consumption compared to those who were always treated, but the reduction is smaller than in the earlier vs later comparison.\footnote{We have always treated customers in this sample as we add to reduce the window of analysis to construct a balance panel}

\textbf{Later vs Earlier Treated:} comparison, contributing 22.0\% to the overall effect, shows that later treated individuals had a significant reduction compared to earlier treated ones, though not as large as the earliest comparison. It is the closest to our two-way fixed effect estimates (-1.244 kWh times 7 \textasciitilde{} -8.708 kWh per week).

\textbf{Treated vs Untreated:} comparison, while only contributing 0.45\% to the overall effect, shows the difference between treated and untreated customers, indicating a moderate reduction in consumption for treated customers.

The Goodman-Bacon Decomposition allows us to see how different comparisons contribute to the overall DiD estimate. A plot of all comparisons is also shown in Figures \ref{fig:bacon1} and \ref{fig:bacon2}. In our case, the most substantial contributions come from comparisons involving \textbf{later treated versus always treated customers}, and \textbf{earlier versus later treated customers}. These results indicate that the timing of adopting Cosy plays a crucial role in the observed reduction in electricity consumption, with earlier adopters showing more significant reductions. Earlier adoptors would have also used Cosy during the 2022-2023 Winter enerhy crisis, potentially leading to larger shift in consumption.

The next biggest contributors is the \textbf{Later vs Earlier Treated} with smaller coefficients. This comparison is incorrect: The DiD approach relies on the assumption that the control group provides a valid counterfactual for the treated group. ``Later vs Earlier Treated'' directly compares units that receive the treatment at different times without considering the pre-treatment period for both groups. This comparison mixes the treatment effects from different time periods, violating the parallel trends assumption.

Motivated by the insights from the Goodman-Bacon decomposition and the need to properly account for staggered adoption, we apply the Callaway and Sant'Anna (2021) approach in Section \ref{sec:santanna}. This method accommodates treatment effect heterogeneity and corrects for timing differences, providing a more robust analysis of the treatment effects over different periods.

By using the Callaway and Sant'Anna approach, we can more accurately estimate the causal impact of Cosy adoption, ensuring that our results are not confounded by inappropriate comparisons and properly reflect the treatment effects across different groups and times.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/bacon_decomposition} 

}

\caption{Bacon Decomposition}\label{fig:bacon1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/bacon_decompostion_subgroup} 

}

\caption{Comparison with DiD Estimate}\label{fig:bacon2}
\end{figure}

\subsection*{Share electricity consumption}\label{share-electricity-consumption}
\addcontentsline{toc}{subsection}{Share electricity consumption}

The table's analysis shows how adopting the Cosy rate plan impacts customers' electricity usage patterns across different times of the day, focusing on the change in the share of daily electricity consumption per period.

\begin{itemize}
\tightlist
\item
  \textbf{Afternoon Cosy Period:} After switching to the Cosy rate, the proportion of electricity used during the afternoon cosy period increased by 6.62 percentage points. This indicates customers are more inclined to consume electricity during these hours under the Cosy rate.
\item
  \textbf{Morning Cosy Period:} The adoption of the Cosy rate led to an even more pronounced increase in electricity use during the morning cosy period, with a 12.56 percentage point rise in its share of daily consumption. This suggests a significant behavioral shift towards consuming more electricity in the morning hours.
\item
  \textbf{Other Times:} Contrarily, there's a decrease in the share of electricity consumption during times not designated as cosy by 14.71 percentage points, reflecting a shift away from electricity usage during these periods.
\item
  \textbf{Peak Rate Times:} The share of daily electricity usage during peak rate times also saw a decrease, falling by 4.75 percentage points. This reduction implies that consumers are adjusting their usage to avoid higher-cost periods.
\end{itemize}

\input{"../tables/did_table_share.tex"}

\subsection*{Heat Pump Installation}\label{heat-pump-installation}
\addcontentsline{toc}{subsection}{Heat Pump Installation}

In this section, I use a sample of Cosy customers that had their heat pump installed by Octopus Energy Service to create an algorythm that detects heat pump installation and apply it to the larger sample.

The data consists of electricity and gas consumption for 69 customers, tracked from 2018 to 2024. The data is available only for those periods when the customers had active accounts with Octopus Energy. Alongside the consumption data, we also have the exact date pf the installation of heat pumps for these customers. Utilizing this data, we employed a machine learning algorithm to identify the timing of heat pump installations and apply it to the larger sample of Cosy customers.

\subsubsection{Data Preparation and Feature Engineering}\label{data-preparation-and-feature-engineering}

The data used includes monthly electricity and gas readings, weather conditions, and installation records. The target is whether or not an Heat Pump is installed for a particular month. At this point, the script is not recursive - meaning that I did not apply it recursively - a customer can have an heat pump detected in January but not April. In spite of this simplication, the algorythm is still quite successful at accuretely detecting heatpumps.

For the heat pump detection algorithm, significant preprocessing steps were taken to enrich the data and make it suitable for machine learning analysis. This included creating rolling averages of gas and electricity consumption to smooth out short-term fluctuations and highlight longer-term trends, which are more indicative of a heat pump's operation. I also calculated differences between consecutive months' readings to capture sudden changes in consumption patterns potentially indicating the installation of a heat pump.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/importance} 

}

\caption{Importance plot from the random forest model}\label{fig:importanceplot}
\end{figure}

\subsubsection{Algorithm Implementation}\label{algorithm-implementation}

The core of the approach was a Random Forest Classifier, a robust machine learning model suitable for classification tasks. The classifier was trained on features such as rolling averages of consumption, consumption, monthly differences in consumption, weather-related variables, and installation data. These features were chosen to effectively distinguish between periods before and after a heat pump installation based on changes in energy usage patterns influenced by the efficiency and operational characteristics of heat pumps.

\subsubsection{Model Training and Evaluation}\label{model-training-and-evaluation}

After splitting the data into training and test sets (70\% versus 30\% given our small sample size), we trained the Random Forest model on the training data, tuning it to identify the presence of a heat pump installation. The model's performance was evaluated on the test dataset using a confusion matrix, which provided a clear picture of its accuracy in correctly identifying actual installations versus non-installations.

\subsubsection{Confusion Matrix}\label{confusion-matrix}

The performance of our heat pump detection algorithm, evaluated through the confusion matrix and associated statistics, provides a comprehensive view of its effectiveness. Here's a detailed breakdown of the results from the model evaluation:

\begin{itemize}
\tightlist
\item
  \textbf{True Negatives (TN):} 387 cases where the model correctly predicted the absence of a heat pump installation.
\item
  \textbf{False Positives (FP):} 15 cases where the model incorrectly predicted a heat pump installation.
\item
  \textbf{False Negatives (FN):} 16 cases where the model failed to detect an existing heat pump installation (these are concentrated druing summer months as shown in Figure \ref{fig:predovertime}).
\item
  \textbf{True Positives (TP):} 174 cases where the model correctly identified the presence of a heat pump installation.
\end{itemize}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/predictions_over_time} 

}

\caption{Prediction Types over Time}\label{fig:predovertime}
\end{figure}

\subsubsection{Model Accuracy and Statistics}\label{model-accuracy-and-statistics}

The overall accuracy of the model was 94.76\%, which indicates that the classifier was able to correctly identify the presence or absence of heat pump installations in a high percentage of cases. The 95\% confidence interval for the accuracy is between 92.65\% and 96.41\%, suggesting a high level of precision in the model's predictions.

\subsubsection{Additional Statistical Measures}\label{additional-statistical-measures}

\begin{itemize}
\tightlist
\item
  \textbf{No Information Rate (NIR):} This is the accuracy that could be achieved by always predicting the most frequent class. Here, it is 68.07\%, significantly lower than the model's accuracy, indicating that the model's predictions are not merely by chance (P-Value \textless{} 2e-16).
\item
  \textbf{Kappa Statistic:} The Kappa value of 0.8797 suggests a very good agreement between the predictions and the actual installations, correcting for the accuracy of random chance.
\item
  \textbf{Mcnemar's Test:} The P-value of 1 for Mcnemar's test indicates that the model's performance is stable across different subsets of the dataset, with no significant bias between the type I and type II errors.
\end{itemize}

\subsubsection{Sensitivity and Specificity}\label{sensitivity-and-specificity}

\begin{itemize}
\tightlist
\item
  \textbf{Sensitivity (Recall):} The model has a sensitivity of 96.03\%, meaning it correctly identifies 96.03\% of the actual installations. This high sensitivity is crucial for ensuring that most heat pump installations are detected.
\item
  \textbf{Specificity:} With a specificity of 92.06\%, the model effectively identifies 92.06\% of cases where no heat pump has been installed, minimizing the instances where installations are falsely detected.
\end{itemize}

\subsubsection{Predictive Values}\label{predictive-values}

\begin{itemize}
\tightlist
\item
  \textbf{Positive Predictive Value (Precision):} The precision of 96.27\% indicates that when the model predicts a heat pump installation, it is correct 96.27\% of the time.
\item
  \textbf{Negative Predictive Value:} The negative predictive value of 91.58\% shows the probability that the absence of a detected installation truly means no installation.
\end{itemize}

\subsubsection{Balanced Accuracy}\label{balanced-accuracy}

\begin{itemize}
\tightlist
\item
  \textbf{Balanced Accuracy:} At 94.05\%, the balanced accuracy, which is the average of sensitivity and specificity, indicates excellent model performance in both detecting installations and confirming non-installations.
\end{itemize}

These metrics collectively demonstrate that the model is highly effective at distinguishing between the presence and absence of heat pump installations in the dataset.

\subsubsection{Limtations of the Current Model}\label{limtations-of-the-current-model}

While the results from the model are highly encouraging, there are some limitations in the current approach that are important to consider for future research and operational improvements:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Skewed Distribution of Installations:}
  A significant limitation in the current dataset is that most heat pump installations occurred after 2022. This skewness can introduce bias into the model, as it might overfit to the characteristics of more recent data. It could affect the model's ability to generalize effectively across other time periods or predict future trends accurately, especially if the market conditions or regulatory frameworks around energy use and equipment installation change.
\item
  \textbf{Small Sample Size:}
  The dataset consists of only 69 customers, which limits the statistical power of the analysis and increases the likelihood of overfitting. With such a small sample, the model's ability to capture the full variability in consumer behavior and installation effects across different demographics and geographic locations is constrained. This can impact the robustness and scalability of the model when applied to a broader population.
\end{enumerate}

\subsubsection{Future Plans to Enhance the Model}\label{future-plans-to-enhance-the-model}

Recognizing these limitations, there are plans to expand the dataset and refine the modeling approach:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Increasing the Dataset Size:}
  To address the issue of a small sample size and improve the model's generalizability, the dataset will be expanded beyond just `Cosy' rate adopters. This expansion will include a wider range of customers who have installed heat pumps, regardless of their rate plan. By broadening the scope of the data, the model will benefit from a more diverse set of consumption patterns and installation timelines, enhancing its accuracy and reliability.
\item
  \textbf{Incorporating a More Diverse Set of Data:}
  Using smart tariff survey will allow us to also use the data from customers that have their heat pump installed further in the past and with different providers. This will not only reduce the potential bias from the current dataset's concentration of recent installations but also enable the model to adapt to a more diverse heat pump users population.
\end{enumerate}

\subsubsection{Predicting the Impact of Heat Pump Installations}\label{predicting-the-impact-of-heat-pump-installations}

To assess the impact of predicted heat pump installations on energy consumption, we extended our analysis to the larger sample of Cosy customers, incorporating the predictions from our machine learning algorithm. We plot the predicted monthly installations in Figure \ref{fig:timeplothpinstall}. We then constructed a regression model to estimate the effects of predicted heat pump installations on monthly electricity consumption. The results are summarized in Table \ref{tab:hp-impact}. We focused on the winter months, as this period is most likely to exhibit significant changes in energy usage patterns due to heating demands.

The regression analysis shows that the installation of a heat pump is associated with a significant increase in monthly electricity consumption by 236.2 kWh, as indicated by the coefficient with a significance level of 0.01 (***). The fixed-effects model accounts for variations across individual customers (MPAN), months, and average heating degree days, ensuring that the observed effects are robust and not driven by unobserved heterogeneity.

\input{"../tables/hp_impact.tex"}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{../graphs/predicted_HP_installations} 

}

\caption{Predicted HP installations}\label{fig:timeplothpinstall}
\end{figure}

\subsection*{Impact of Cosy controlling for HP installation}\label{impact-of-cosy-controlling-for-hp-installation}
\addcontentsline{toc}{subsection}{Impact of Cosy controlling for HP installation}

\begin{landscape}
\input{"../tables/did_hp_install.tex"}
\end{landscape}

\subsection*{Event study}\label{event-study}
\addcontentsline{toc}{subsection}{Event study}

We run the following model by period for all customers that have adopted Cosy in the past year:

\[Consumption_{it} = \sum^W _{w={-52, -9, ..., 1, ..,52}} \alpha_w WeeksSinceCosy^w_{it} + X\beta + \delta_t +  \gamma_i +  \epsilon_{it} \]
where:
- \(WeeksSinceCosy^w_{it}\) is a categorical variable equals to the number of weeks before and after the adoption of Cosy. We use the week prior adoption as omitted category.

The charts show the event study coefficients for each specified period. We find that coefficients are consistent with those from the difference-in-differences analysis for the Morning and Afternoon Cosy periods.

Interestingly, the pre and opost trends don't appear to be as stable, almost indicating an overall decrease/increase in consumption overtime per period.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{did-update_files/figure-latex/event-study-period-1} 

}

\caption{Event Study Analsyis}\label{fig:event-study-period-1}
\end{figure}
\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{did-update_files/figure-latex/event-study-period-2} 

}

\caption{Event Study Analsyis}\label{fig:event-study-period-2}
\end{figure}
\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{did-update_files/figure-latex/event-study-period-3} 

}

\caption{Event Study Analsyis}\label{fig:event-study-period-3}
\end{figure}
\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth,]{did-update_files/figure-latex/event-study-period-4} 

}

\caption{Event Study Analsyis}\label{fig:event-study-period-4}
\end{figure}

\end{document}
