---
title: "EV detection"
author: "Louise Bernard"
date: "2024-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Detect Ev

```{r detect-ev}

library(data.table)
library(furrr)

# Initialize parallel processing
plan(multisession)

# List all files matching the pattern
hourly_files <- list.files("../data/input", pattern = "cosy_-_hh_consumption_2024", full.names = TRUE)

# Read the files in parallel and bind them
combined_df <- future_map(hourly_files, fread) %>%
  rbindlist()

```

```{r events, eval=FALSE}
# # unique mpans 
# sample_mpans <- sample(unique(combined_df$mpan), 100)

# Assuming combined_df is already defined and contains the necessary columns
combined_df2 <- combined_df %>%
  mutate(high_consumption = read_value > 3.5) %>%
  group_by(mpan) %>%
  arrange(mpan, interval_start) %>%
  mutate(high_consumption_indicator = ifelse(high_consumption, cumsum(c(1, diff(high_consumption)) == 0), 0)) %>%
  mutate(grp = cumsum(high_consumption_indicator == 0)) %>%
  group_by(grp, mpan) %>%
  mutate(high_consumption_indicator = ifelse(high_consumption == 0, 0, row_number())) %>%
  filter(high_consumption != 0) %>%
  summarise(event_length = max(high_consumption_indicator),
            event_start = min(interval_start)) %>%
  ungroup() %>%
  mutate(is_event = as.numeric(event_length >= 4 & event_length <= 12))

# Define charging events and check for consecutive weeks
charging_events <- combined_df2 %>%
  filter(is_event == 1) %>%
  mutate(event_week = floor_date(as.Date(event_start), "week")) %>%
  group_by(mpan, event_week) %>%
  summarise(event_count = n(), .groups = 'drop') %>%
  arrange(mpan, event_week) %>%
  ungroup()

# Identify MPANs with EV based on consecutive weeks
ev_mpan <- charging_events %>%
  group_by(mpan) %>%
  mutate(week_diff = c(0, diff(event_week)/7))%>%
  mutate(consecutive_weeks = cumsum(week_diff > 1)) %>%
  group_by(mpan, consecutive_weeks) %>%
  summarise(weeks_of_charging = n(), 
            first_week = min(event_week), 
            .groups = 'drop') %>%
  filter(weeks_of_charging >= 2) %>%
  group_by(mpan) %>%
  summarise(ev_start = min(first_week)-weeks(2), .groups = 'drop')

saveRDS(ev_mpan, "../data/scratch/ev_mpan.RDS")

rm(combined_df2, charging_events, ev_mpan)
gc()
```
